name: CI Pipeline

on:
  push:
    branches:
      - staging

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      working-directory: /home/mscvie/ASP/AbschlussprojektCloud2023/backend-server

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install pip
        run: |
          python -m pip install --upgrade pip

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run tests
        run: |
          python -m unittest discover -s tests


